server:
  port: 8080

spring:
  application:
    name: oauth-server
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
        namespace: mes-dev
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

logging:
  path: ./logs
  name: ${spring.application.name}