server:
  port: 8080

spring:
  application:
    name: oauth-server
  cloud:
    nacos:
      discovery:
        server-addr: http://101.101.101.2:31396
        namespace: mes-dev
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

logging:
  path: ./logs
  name: ${spring.application.name}