// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcProto.proto

package xingyu.lu.lab.grpc.facade.builder;

/**
 * Protobuf type {@code xingyu.lu.lab.grpc.facade.XGrpcReply}
 */
public final class XGrpcReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xingyu.lu.lab.grpc.facade.XGrpcReply)
    XGrpcReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use XGrpcReply.newBuilder() to construct.
  private XGrpcReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private XGrpcReply() {
    errorCode_ = "";
    errorMessage_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new XGrpcReply();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private XGrpcReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            isSuccess_ = input.readBool();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            errorCode_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            errorMessage_ = s;
            break;
          }
          case 34: {
            com.google.protobuf.Any.Builder subBuilder = null;
            if (bizData_ != null) {
              subBuilder = bizData_.toBuilder();
            }
            bizData_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bizData_);
              bizData_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return XGrpcProto.internal_static_xingyu_lu_lab_grpc_facade_XGrpcReply_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return XGrpcProto.internal_static_xingyu_lu_lab_grpc_facade_XGrpcReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            XGrpcReply.class, Builder.class);
  }

  public static final int ISSUCCESS_FIELD_NUMBER = 1;
  private boolean isSuccess_;
  /**
   * <code>bool isSuccess = 1;</code>
   * @return The isSuccess.
   */
  @Override
  public boolean getIsSuccess() {
    return isSuccess_;
  }

  public static final int ERRORCODE_FIELD_NUMBER = 2;
  private volatile Object errorCode_;
  /**
   * <code>string errorCode = 2;</code>
   * @return The errorCode.
   */
  @Override
  public String getErrorCode() {
    Object ref = errorCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      errorCode_ = s;
      return s;
    }
  }
  /**
   * <code>string errorCode = 2;</code>
   * @return The bytes for errorCode.
   */
  @Override
  public com.google.protobuf.ByteString
      getErrorCodeBytes() {
    Object ref = errorCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      errorCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERRORMESSAGE_FIELD_NUMBER = 3;
  private volatile Object errorMessage_;
  /**
   * <code>string errorMessage = 3;</code>
   * @return The errorMessage.
   */
  @Override
  public String getErrorMessage() {
    Object ref = errorMessage_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string errorMessage = 3;</code>
   * @return The bytes for errorMessage.
   */
  @Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    Object ref = errorMessage_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIZDATA_FIELD_NUMBER = 4;
  private com.google.protobuf.Any bizData_;
  /**
   * <code>.google.protobuf.Any bizData = 4;</code>
   * @return Whether the bizData field is set.
   */
  @Override
  public boolean hasBizData() {
    return bizData_ != null;
  }
  /**
   * <code>.google.protobuf.Any bizData = 4;</code>
   * @return The bizData.
   */
  @Override
  public com.google.protobuf.Any getBizData() {
    return bizData_ == null ? com.google.protobuf.Any.getDefaultInstance() : bizData_;
  }
  /**
   * <code>.google.protobuf.Any bizData = 4;</code>
   */
  @Override
  public com.google.protobuf.AnyOrBuilder getBizDataOrBuilder() {
    return getBizData();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isSuccess_ != false) {
      output.writeBool(1, isSuccess_);
    }
    if (!getErrorCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorCode_);
    }
    if (!getErrorMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorMessage_);
    }
    if (bizData_ != null) {
      output.writeMessage(4, getBizData());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isSuccess_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isSuccess_);
    }
    if (!getErrorCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorCode_);
    }
    if (!getErrorMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorMessage_);
    }
    if (bizData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getBizData());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof XGrpcReply)) {
      return super.equals(obj);
    }
    XGrpcReply other = (XGrpcReply) obj;

    if (getIsSuccess()
        != other.getIsSuccess()) return false;
    if (!getErrorCode()
        .equals(other.getErrorCode())) return false;
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (hasBizData() != other.hasBizData()) return false;
    if (hasBizData()) {
      if (!getBizData()
          .equals(other.getBizData())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ISSUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSuccess());
    hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorCode().hashCode();
    hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    if (hasBizData()) {
      hash = (37 * hash) + BIZDATA_FIELD_NUMBER;
      hash = (53 * hash) + getBizData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static XGrpcReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static XGrpcReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static XGrpcReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static XGrpcReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static XGrpcReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static XGrpcReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static XGrpcReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static XGrpcReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static XGrpcReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static XGrpcReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static XGrpcReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static XGrpcReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(XGrpcReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xingyu.lu.lab.grpc.facade.XGrpcReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xingyu.lu.lab.grpc.facade.XGrpcReply)
      XGrpcReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return XGrpcProto.internal_static_xingyu_lu_lab_grpc_facade_XGrpcReply_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return XGrpcProto.internal_static_xingyu_lu_lab_grpc_facade_XGrpcReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              XGrpcReply.class, Builder.class);
    }

    // Construct using xingyu.lu.lab.grpc.facade.builder.XGrpcReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      isSuccess_ = false;

      errorCode_ = "";

      errorMessage_ = "";

      if (bizDataBuilder_ == null) {
        bizData_ = null;
      } else {
        bizData_ = null;
        bizDataBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return XGrpcProto.internal_static_xingyu_lu_lab_grpc_facade_XGrpcReply_descriptor;
    }

    @Override
    public XGrpcReply getDefaultInstanceForType() {
      return XGrpcReply.getDefaultInstance();
    }

    @Override
    public XGrpcReply build() {
      XGrpcReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public XGrpcReply buildPartial() {
      XGrpcReply result = new XGrpcReply(this);
      result.isSuccess_ = isSuccess_;
      result.errorCode_ = errorCode_;
      result.errorMessage_ = errorMessage_;
      if (bizDataBuilder_ == null) {
        result.bizData_ = bizData_;
      } else {
        result.bizData_ = bizDataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof XGrpcReply) {
        return mergeFrom((XGrpcReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(XGrpcReply other) {
      if (other == XGrpcReply.getDefaultInstance()) return this;
      if (other.getIsSuccess() != false) {
        setIsSuccess(other.getIsSuccess());
      }
      if (!other.getErrorCode().isEmpty()) {
        errorCode_ = other.errorCode_;
        onChanged();
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        onChanged();
      }
      if (other.hasBizData()) {
        mergeBizData(other.getBizData());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      XGrpcReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (XGrpcReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean isSuccess_ ;
    /**
     * <code>bool isSuccess = 1;</code>
     * @return The isSuccess.
     */
    @Override
    public boolean getIsSuccess() {
      return isSuccess_;
    }
    /**
     * <code>bool isSuccess = 1;</code>
     * @param value The isSuccess to set.
     * @return This builder for chaining.
     */
    public Builder setIsSuccess(boolean value) {
      
      isSuccess_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isSuccess = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSuccess() {
      
      isSuccess_ = false;
      onChanged();
      return this;
    }

    private Object errorCode_ = "";
    /**
     * <code>string errorCode = 2;</code>
     * @return The errorCode.
     */
    public String getErrorCode() {
      Object ref = errorCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        errorCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string errorCode = 2;</code>
     * @return The bytes for errorCode.
     */
    public com.google.protobuf.ByteString
        getErrorCodeBytes() {
      Object ref = errorCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errorCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string errorCode = 2;</code>
     * @param value The errorCode to set.
     * @return This builder for chaining.
     */
    public Builder setErrorCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string errorCode = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorCode() {
      
      errorCode_ = getDefaultInstance().getErrorCode();
      onChanged();
      return this;
    }
    /**
     * <code>string errorCode = 2;</code>
     * @param value The bytes for errorCode to set.
     * @return This builder for chaining.
     */
    public Builder setErrorCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorCode_ = value;
      onChanged();
      return this;
    }

    private Object errorMessage_ = "";
    /**
     * <code>string errorMessage = 3;</code>
     * @return The errorMessage.
     */
    public String getErrorMessage() {
      Object ref = errorMessage_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string errorMessage = 3;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string errorMessage = 3;</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string errorMessage = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      
      errorMessage_ = getDefaultInstance().getErrorMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string errorMessage = 3;</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorMessage_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Any bizData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> bizDataBuilder_;
    /**
     * <code>.google.protobuf.Any bizData = 4;</code>
     * @return Whether the bizData field is set.
     */
    public boolean hasBizData() {
      return bizDataBuilder_ != null || bizData_ != null;
    }
    /**
     * <code>.google.protobuf.Any bizData = 4;</code>
     * @return The bizData.
     */
    public com.google.protobuf.Any getBizData() {
      if (bizDataBuilder_ == null) {
        return bizData_ == null ? com.google.protobuf.Any.getDefaultInstance() : bizData_;
      } else {
        return bizDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Any bizData = 4;</code>
     */
    public Builder setBizData(com.google.protobuf.Any value) {
      if (bizDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bizData_ = value;
        onChanged();
      } else {
        bizDataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any bizData = 4;</code>
     */
    public Builder setBizData(
        com.google.protobuf.Any.Builder builderForValue) {
      if (bizDataBuilder_ == null) {
        bizData_ = builderForValue.build();
        onChanged();
      } else {
        bizDataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any bizData = 4;</code>
     */
    public Builder mergeBizData(com.google.protobuf.Any value) {
      if (bizDataBuilder_ == null) {
        if (bizData_ != null) {
          bizData_ =
            com.google.protobuf.Any.newBuilder(bizData_).mergeFrom(value).buildPartial();
        } else {
          bizData_ = value;
        }
        onChanged();
      } else {
        bizDataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any bizData = 4;</code>
     */
    public Builder clearBizData() {
      if (bizDataBuilder_ == null) {
        bizData_ = null;
        onChanged();
      } else {
        bizData_ = null;
        bizDataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any bizData = 4;</code>
     */
    public com.google.protobuf.Any.Builder getBizDataBuilder() {
      
      onChanged();
      return getBizDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Any bizData = 4;</code>
     */
    public com.google.protobuf.AnyOrBuilder getBizDataOrBuilder() {
      if (bizDataBuilder_ != null) {
        return bizDataBuilder_.getMessageOrBuilder();
      } else {
        return bizData_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : bizData_;
      }
    }
    /**
     * <code>.google.protobuf.Any bizData = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getBizDataFieldBuilder() {
      if (bizDataBuilder_ == null) {
        bizDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getBizData(),
                getParentForChildren(),
                isClean());
        bizData_ = null;
      }
      return bizDataBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xingyu.lu.lab.grpc.facade.XGrpcReply)
  }

  // @@protoc_insertion_point(class_scope:xingyu.lu.lab.grpc.facade.XGrpcReply)
  private static final XGrpcReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new XGrpcReply();
  }

  public static XGrpcReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<XGrpcReply>
      PARSER = new com.google.protobuf.AbstractParser<XGrpcReply>() {
    @Override
    public XGrpcReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new XGrpcReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<XGrpcReply> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<XGrpcReply> getParserForType() {
    return PARSER;
  }

  @Override
  public XGrpcReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

