// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcProto.proto

package xingyu.lu.lab.grpc.facade.builder;

/**
 * Protobuf type {@code xingyu.lu.lab.grpc.facade.XGrpcRequest}
 */
public final class XGrpcRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:xingyu.lu.lab.grpc.facade.XGrpcRequest)
    XGrpcRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use XGrpcRequest.newBuilder() to construct.
  private XGrpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private XGrpcRequest() {
    appId_ = "";
    method_ = "";
    sign_ = "";
    version_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new XGrpcRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private XGrpcRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            appId_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            method_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            sign_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          case 42: {
            com.google.protobuf.Any.Builder subBuilder = null;
            if (bizContent_ != null) {
              subBuilder = bizContent_.toBuilder();
            }
            bizContent_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bizContent_);
              bizContent_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return XGrpcProto.internal_static_xingyu_lu_lab_grpc_facade_XGrpcRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return XGrpcProto.internal_static_xingyu_lu_lab_grpc_facade_XGrpcRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            XGrpcRequest.class, Builder.class);
  }

  public static final int APPID_FIELD_NUMBER = 1;
  private volatile Object appId_;
  /**
   * <code>string appId = 1;</code>
   * @return The appId.
   */
  @Override
  public String getAppId() {
    Object ref = appId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      appId_ = s;
      return s;
    }
  }
  /**
   * <code>string appId = 1;</code>
   * @return The bytes for appId.
   */
  @Override
  public com.google.protobuf.ByteString
      getAppIdBytes() {
    Object ref = appId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      appId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHOD_FIELD_NUMBER = 2;
  private volatile Object method_;
  /**
   * <code>string method = 2;</code>
   * @return The method.
   */
  @Override
  public String getMethod() {
    Object ref = method_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      method_ = s;
      return s;
    }
  }
  /**
   * <code>string method = 2;</code>
   * @return The bytes for method.
   */
  @Override
  public com.google.protobuf.ByteString
      getMethodBytes() {
    Object ref = method_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      method_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIGN_FIELD_NUMBER = 3;
  private volatile Object sign_;
  /**
   * <code>string sign = 3;</code>
   * @return The sign.
   */
  @Override
  public String getSign() {
    Object ref = sign_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      sign_ = s;
      return s;
    }
  }
  /**
   * <code>string sign = 3;</code>
   * @return The bytes for sign.
   */
  @Override
  public com.google.protobuf.ByteString
      getSignBytes() {
    Object ref = sign_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sign_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 4;
  private volatile Object version_;
  /**
   * <code>string version = 4;</code>
   * @return The version.
   */
  @Override
  public String getVersion() {
    Object ref = version_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 4;</code>
   * @return The bytes for version.
   */
  @Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    Object ref = version_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIZCONTENT_FIELD_NUMBER = 5;
  private com.google.protobuf.Any bizContent_;
  /**
   * <code>.google.protobuf.Any bizContent = 5;</code>
   * @return Whether the bizContent field is set.
   */
  @Override
  public boolean hasBizContent() {
    return bizContent_ != null;
  }
  /**
   * <code>.google.protobuf.Any bizContent = 5;</code>
   * @return The bizContent.
   */
  @Override
  public com.google.protobuf.Any getBizContent() {
    return bizContent_ == null ? com.google.protobuf.Any.getDefaultInstance() : bizContent_;
  }
  /**
   * <code>.google.protobuf.Any bizContent = 5;</code>
   */
  @Override
  public com.google.protobuf.AnyOrBuilder getBizContentOrBuilder() {
    return getBizContent();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAppIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appId_);
    }
    if (!getMethodBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, method_);
    }
    if (!getSignBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sign_);
    }
    if (!getVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, version_);
    }
    if (bizContent_ != null) {
      output.writeMessage(5, getBizContent());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAppIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appId_);
    }
    if (!getMethodBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, method_);
    }
    if (!getSignBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sign_);
    }
    if (!getVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, version_);
    }
    if (bizContent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getBizContent());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof XGrpcRequest)) {
      return super.equals(obj);
    }
    XGrpcRequest other = (XGrpcRequest) obj;

    if (!getAppId()
        .equals(other.getAppId())) return false;
    if (!getMethod()
        .equals(other.getMethod())) return false;
    if (!getSign()
        .equals(other.getSign())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (hasBizContent() != other.hasBizContent()) return false;
    if (hasBizContent()) {
      if (!getBizContent()
          .equals(other.getBizContent())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + APPID_FIELD_NUMBER;
    hash = (53 * hash) + getAppId().hashCode();
    hash = (37 * hash) + METHOD_FIELD_NUMBER;
    hash = (53 * hash) + getMethod().hashCode();
    hash = (37 * hash) + SIGN_FIELD_NUMBER;
    hash = (53 * hash) + getSign().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    if (hasBizContent()) {
      hash = (37 * hash) + BIZCONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getBizContent().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static XGrpcRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static XGrpcRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static XGrpcRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static XGrpcRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static XGrpcRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static XGrpcRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static XGrpcRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static XGrpcRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static XGrpcRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static XGrpcRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static XGrpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static XGrpcRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(XGrpcRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xingyu.lu.lab.grpc.facade.XGrpcRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xingyu.lu.lab.grpc.facade.XGrpcRequest)
      XGrpcRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return XGrpcProto.internal_static_xingyu_lu_lab_grpc_facade_XGrpcRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return XGrpcProto.internal_static_xingyu_lu_lab_grpc_facade_XGrpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              XGrpcRequest.class, Builder.class);
    }

    // Construct using xingyu.lu.lab.grpc.facade.builder.XGrpcRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      appId_ = "";

      method_ = "";

      sign_ = "";

      version_ = "";

      if (bizContentBuilder_ == null) {
        bizContent_ = null;
      } else {
        bizContent_ = null;
        bizContentBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return XGrpcProto.internal_static_xingyu_lu_lab_grpc_facade_XGrpcRequest_descriptor;
    }

    @Override
    public XGrpcRequest getDefaultInstanceForType() {
      return XGrpcRequest.getDefaultInstance();
    }

    @Override
    public XGrpcRequest build() {
      XGrpcRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public XGrpcRequest buildPartial() {
      XGrpcRequest result = new XGrpcRequest(this);
      result.appId_ = appId_;
      result.method_ = method_;
      result.sign_ = sign_;
      result.version_ = version_;
      if (bizContentBuilder_ == null) {
        result.bizContent_ = bizContent_;
      } else {
        result.bizContent_ = bizContentBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof XGrpcRequest) {
        return mergeFrom((XGrpcRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(XGrpcRequest other) {
      if (other == XGrpcRequest.getDefaultInstance()) return this;
      if (!other.getAppId().isEmpty()) {
        appId_ = other.appId_;
        onChanged();
      }
      if (!other.getMethod().isEmpty()) {
        method_ = other.method_;
        onChanged();
      }
      if (!other.getSign().isEmpty()) {
        sign_ = other.sign_;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (other.hasBizContent()) {
        mergeBizContent(other.getBizContent());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      XGrpcRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (XGrpcRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object appId_ = "";
    /**
     * <code>string appId = 1;</code>
     * @return The appId.
     */
    public String getAppId() {
      Object ref = appId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string appId = 1;</code>
     * @return The bytes for appId.
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      Object ref = appId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string appId = 1;</code>
     * @param value The appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      appId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string appId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppId() {
      
      appId_ = getDefaultInstance().getAppId();
      onChanged();
      return this;
    }
    /**
     * <code>string appId = 1;</code>
     * @param value The bytes for appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      appId_ = value;
      onChanged();
      return this;
    }

    private Object method_ = "";
    /**
     * <code>string method = 2;</code>
     * @return The method.
     */
    public String getMethod() {
      Object ref = method_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        method_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string method = 2;</code>
     * @return The bytes for method.
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      Object ref = method_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string method = 2;</code>
     * @param value The method to set.
     * @return This builder for chaining.
     */
    public Builder setMethod(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      method_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string method = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMethod() {
      
      method_ = getDefaultInstance().getMethod();
      onChanged();
      return this;
    }
    /**
     * <code>string method = 2;</code>
     * @param value The bytes for method to set.
     * @return This builder for chaining.
     */
    public Builder setMethodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      method_ = value;
      onChanged();
      return this;
    }

    private Object sign_ = "";
    /**
     * <code>string sign = 3;</code>
     * @return The sign.
     */
    public String getSign() {
      Object ref = sign_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sign_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string sign = 3;</code>
     * @return The bytes for sign.
     */
    public com.google.protobuf.ByteString
        getSignBytes() {
      Object ref = sign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sign = 3;</code>
     * @param value The sign to set.
     * @return This builder for chaining.
     */
    public Builder setSign(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sign_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sign = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSign() {
      
      sign_ = getDefaultInstance().getSign();
      onChanged();
      return this;
    }
    /**
     * <code>string sign = 3;</code>
     * @param value The bytes for sign to set.
     * @return This builder for chaining.
     */
    public Builder setSignBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sign_ = value;
      onChanged();
      return this;
    }

    private Object version_ = "";
    /**
     * <code>string version = 4;</code>
     * @return The version.
     */
    public String getVersion() {
      Object ref = version_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string version = 4;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 4;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string version = 4;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Any bizContent_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> bizContentBuilder_;
    /**
     * <code>.google.protobuf.Any bizContent = 5;</code>
     * @return Whether the bizContent field is set.
     */
    public boolean hasBizContent() {
      return bizContentBuilder_ != null || bizContent_ != null;
    }
    /**
     * <code>.google.protobuf.Any bizContent = 5;</code>
     * @return The bizContent.
     */
    public com.google.protobuf.Any getBizContent() {
      if (bizContentBuilder_ == null) {
        return bizContent_ == null ? com.google.protobuf.Any.getDefaultInstance() : bizContent_;
      } else {
        return bizContentBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Any bizContent = 5;</code>
     */
    public Builder setBizContent(com.google.protobuf.Any value) {
      if (bizContentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bizContent_ = value;
        onChanged();
      } else {
        bizContentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any bizContent = 5;</code>
     */
    public Builder setBizContent(
        com.google.protobuf.Any.Builder builderForValue) {
      if (bizContentBuilder_ == null) {
        bizContent_ = builderForValue.build();
        onChanged();
      } else {
        bizContentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any bizContent = 5;</code>
     */
    public Builder mergeBizContent(com.google.protobuf.Any value) {
      if (bizContentBuilder_ == null) {
        if (bizContent_ != null) {
          bizContent_ =
            com.google.protobuf.Any.newBuilder(bizContent_).mergeFrom(value).buildPartial();
        } else {
          bizContent_ = value;
        }
        onChanged();
      } else {
        bizContentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any bizContent = 5;</code>
     */
    public Builder clearBizContent() {
      if (bizContentBuilder_ == null) {
        bizContent_ = null;
        onChanged();
      } else {
        bizContent_ = null;
        bizContentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any bizContent = 5;</code>
     */
    public com.google.protobuf.Any.Builder getBizContentBuilder() {
      
      onChanged();
      return getBizContentFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Any bizContent = 5;</code>
     */
    public com.google.protobuf.AnyOrBuilder getBizContentOrBuilder() {
      if (bizContentBuilder_ != null) {
        return bizContentBuilder_.getMessageOrBuilder();
      } else {
        return bizContent_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : bizContent_;
      }
    }
    /**
     * <code>.google.protobuf.Any bizContent = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getBizContentFieldBuilder() {
      if (bizContentBuilder_ == null) {
        bizContentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getBizContent(),
                getParentForChildren(),
                isClean());
        bizContent_ = null;
      }
      return bizContentBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:xingyu.lu.lab.grpc.facade.XGrpcRequest)
  }

  // @@protoc_insertion_point(class_scope:xingyu.lu.lab.grpc.facade.XGrpcRequest)
  private static final XGrpcRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new XGrpcRequest();
  }

  public static XGrpcRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<XGrpcRequest>
      PARSER = new com.google.protobuf.AbstractParser<XGrpcRequest>() {
    @Override
    public XGrpcRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new XGrpcRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<XGrpcRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<XGrpcRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public XGrpcRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

