// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcProto.proto

package xingyu.lu.lab.grpc.facade.builder;

public interface XGrpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xingyu.lu.lab.grpc.facade.XGrpcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string appId = 1;</code>
   * @return The appId.
   */
  String getAppId();
  /**
   * <code>string appId = 1;</code>
   * @return The bytes for appId.
   */
  com.google.protobuf.ByteString
      getAppIdBytes();

  /**
   * <code>string method = 2;</code>
   * @return The method.
   */
  String getMethod();
  /**
   * <code>string method = 2;</code>
   * @return The bytes for method.
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>string sign = 3;</code>
   * @return The sign.
   */
  String getSign();
  /**
   * <code>string sign = 3;</code>
   * @return The bytes for sign.
   */
  com.google.protobuf.ByteString
      getSignBytes();

  /**
   * <code>string version = 4;</code>
   * @return The version.
   */
  String getVersion();
  /**
   * <code>string version = 4;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>.google.protobuf.Any bizContent = 5;</code>
   * @return Whether the bizContent field is set.
   */
  boolean hasBizContent();
  /**
   * <code>.google.protobuf.Any bizContent = 5;</code>
   * @return The bizContent.
   */
  com.google.protobuf.Any getBizContent();
  /**
   * <code>.google.protobuf.Any bizContent = 5;</code>
   */
  com.google.protobuf.AnyOrBuilder getBizContentOrBuilder();
}
