// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcProto.proto

package xingyu.lu.lab.grpc.facade.builder;

public final class XGrpcProto {
  private XGrpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xingyu_lu_lab_grpc_facade_XGrpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xingyu_lu_lab_grpc_facade_XGrpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xingyu_lu_lab_grpc_facade_XGrpcReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xingyu_lu_lab_grpc_facade_XGrpcReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017GrpcProto.proto\022\031xingyu.lu.lab.grpc.fa" +
      "cade\032\031google/protobuf/any.proto\"v\n\014XGrpc" +
      "Request\022\r\n\005appId\030\001 \001(\t\022\016\n\006method\030\002 \001(\t\022\014" +
      "\n\004sign\030\003 \001(\t\022\017\n\007version\030\004 \001(\t\022(\n\nbizCont" +
      "ent\030\005 \001(\0132\024.google.protobuf.Any\"o\n\nXGrpc" +
      "Reply\022\021\n\tisSuccess\030\001 \001(\010\022\021\n\terrorCode\030\002 " +
      "\001(\t\022\024\n\014errorMessage\030\003 \001(\t\022%\n\007bizData\030\004 \001" +
      "(\0132\024.google.protobuf.Any2n\n\014XGrpcService" +
      "\022^\n\nechoGrpc4J\022\'.xingyu.lu.lab.grpc.faca" +
      "de.XGrpcRequest\032%.xingyu.lu.lab.grpc.fac" +
      "ade.XGrpcReply\"\000B1\n!xingyu.lu.lab.grpc.f" +
      "acade.builderB\nXGrpcProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_xingyu_lu_lab_grpc_facade_XGrpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xingyu_lu_lab_grpc_facade_XGrpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xingyu_lu_lab_grpc_facade_XGrpcRequest_descriptor,
        new String[] { "AppId", "Method", "Sign", "Version", "BizContent", });
    internal_static_xingyu_lu_lab_grpc_facade_XGrpcReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_xingyu_lu_lab_grpc_facade_XGrpcReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xingyu_lu_lab_grpc_facade_XGrpcReply_descriptor,
        new String[] { "IsSuccess", "ErrorCode", "ErrorMessage", "BizData", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
