server:
  port: 8080
spring:
  application:
    name: grpc-server
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
        namespace: dev

grpc:
  server:
    port: 50101