hserver:
  port: 8081
spring:
  application:
    name: grpc-client
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
        namespace: dev
logging:
  path: ./logs
  name: grpc-client
grpc:
  client:
    grpc-server:
      address: 'discovery:///grpc-server'
      #      address: 'dns:///grpc-server.namespace.svc.cluster.local:54321'
      #      address: 'static://127.0.0.1:9991'
      enableKeepAlive: true