server:
  port: 18002

spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: aa23932f-daff-4188-994f-ceff3f8d9749
        group: local
      config:
        server-addr: 127.0.0.1:8848
        namespace: aa23932f-daff-4188-994f-ceff3f8d9749
        group: local
        name: spring-datatsource
        file-extension: yaml
  config:
    #  Nacos 在 Cloud 中 dataId 的完整格式：${prefix}-${spring.profiles.active}.${file-extension}
    #  prefix 默认为 spring.application.name 的值
    import:
      - optional:nacos:${spring.application.name}-${spring.cloud.nacos.config.name}.${spring.cloud.nacos.config.file-extension}

logging:
  level:
    com.baomidou: debug
    com.alibaba.cloud.nacos.configdata: info
