server:
  port: 8080

spring:
  application:
    name: unified-auth
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
        namespace: dev
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
    dynamic:
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 1000
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      primary: auth-ds
      datasource:
        # 数据源配置
        auth-ds:
          url: jdbc:mysql://127.0.0.1:3306/oauth?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: Aa123456

mybatis-plus:
  # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
#    主键类型  0:"数据库ID自增"
#             1:"该类型为未设置主键类型"
#             2:"用户输入ID"
#             3:"全局唯一ID (数字类型唯一ID)"
#             4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)"
#    db-config:
#      id-type: 4
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true


logging:
  path: ./logs
  name: ${spring.application.name}