// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcXModule.proto

package xingyu.lu.individual.svc.sofa.boot.facade.builder;

public interface GrpcXReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xingyu.lu.individual.svc.sofa.boot.facade.GrpcXReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isSuccess = 1;</code>
   */
  boolean getIsSuccess();

  /**
   * <code>string errorCode = 2;</code>
   */
  String getErrorCode();
  /**
   * <code>string errorCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorCodeBytes();

  /**
   * <code>string errorMessage = 3;</code>
   */
  String getErrorMessage();
  /**
   * <code>string errorMessage = 3;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>string bizData = 4;</code>
   */
  String getBizData();
  /**
   * <code>string bizData = 4;</code>
   */
  com.google.protobuf.ByteString
      getBizDataBytes();
}
