// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcXModule.proto

package xingyu.lu.individual.svc.sofa.boot.facade.builder;

public final class GrpcXModule {
  private GrpcXModule() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xingyu_lu_individual_svc_sofa_boot_facade_GrpcXRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xingyu_lu_individual_svc_sofa_boot_facade_GrpcXRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xingyu_lu_individual_svc_sofa_boot_facade_GrpcXReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xingyu_lu_individual_svc_sofa_boot_facade_GrpcXReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021GrpcXModule.proto\022)xingyu.lu.individua" +
      "l.svc.sofa.boot.facade\"`\n\014GrpcXRequest\022\r" +
      "\n\005appId\030\001 \001(\t\022\016\n\006method\030\002 \001(\t\022\014\n\004sign\030\003 " +
      "\001(\t\022\017\n\007version\030\004 \001(\t\022\022\n\nbizContent\030\005 \001(\t" +
      "\"Y\n\nGrpcXReply\022\021\n\tisSuccess\030\001 \001(\010\022\021\n\terr" +
      "orCode\030\002 \001(\t\022\024\n\014errorMessage\030\003 \001(\t\022\017\n\007bi" +
      "zData\030\004 \001(\t2\211\001\n\010XService\022}\n\tGrpcXCall\0227." +
      "xingyu.lu.individual.svc.sofa.boot.facad" +
      "e.GrpcXRequest\0325.xingyu.lu.individual.sv" +
      "c.sofa.boot.facade.GrpcXReply\"\000BB\n1xingy" +
      "u.lu.individual.svc.sofa.boot.facade.bui" +
      "lderB\013GrpcXModuleP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_xingyu_lu_individual_svc_sofa_boot_facade_GrpcXRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xingyu_lu_individual_svc_sofa_boot_facade_GrpcXRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xingyu_lu_individual_svc_sofa_boot_facade_GrpcXRequest_descriptor,
        new String[] { "AppId", "Method", "Sign", "Version", "BizContent", });
    internal_static_xingyu_lu_individual_svc_sofa_boot_facade_GrpcXReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_xingyu_lu_individual_svc_sofa_boot_facade_GrpcXReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xingyu_lu_individual_svc_sofa_boot_facade_GrpcXReply_descriptor,
        new String[] { "IsSuccess", "ErrorCode", "ErrorMessage", "BizData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
