// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcXModule.proto

package xingyu.lu.individual.svc.sofa.boot.facade.builder;

public interface GrpcXRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xingyu.lu.individual.svc.sofa.boot.facade.GrpcXRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string appId = 1;</code>
   */
  String getAppId();
  /**
   * <code>string appId = 1;</code>
   */
  com.google.protobuf.ByteString
      getAppIdBytes();

  /**
   * <code>string method = 2;</code>
   */
  String getMethod();
  /**
   * <code>string method = 2;</code>
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>string sign = 3;</code>
   */
  String getSign();
  /**
   * <code>string sign = 3;</code>
   */
  com.google.protobuf.ByteString
      getSignBytes();

  /**
   * <code>string version = 4;</code>
   */
  String getVersion();
  /**
   * <code>string version = 4;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string bizContent = 5;</code>
   */
  String getBizContent();
  /**
   * <code>string bizContent = 5;</code>
   */
  com.google.protobuf.ByteString
      getBizContentBytes();
}
