package xingyu.lu.review.db.multiple.domain.cluster;

import java.util.Date;

public class UserOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.id
     *
     * @mbggenerated
     */
    /**
	   * id
	   * default = null
	   * length = 10
	   */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.order_no
     *
     * @mbggenerated
     */
    /**
	   * 订单号
	   * default = null
	   * length = 50
	   */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.create_time
     *
     * @mbggenerated
     */
    /**
	   * 
	   * default = null
	   * length = 19
	   */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.id
     *
     * @return the value of user_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.id
     *
     * @param id the value for user_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.order_no
     *
     * @return the value of user_order.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.order_no
     *
     * @param orderNo the value for user_order.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.create_time
     *
     * @return the value of user_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.create_time
     *
     * @param createTime the value for user_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}