spring:
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        # 路由的编号
        - id: nacos_route
          # 路由目标地址
          uri: http://localhost:8848
          # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
          predicates:
            - Path=/nacos/**
        # cloud_svc_provider
        - id: cloud_svc_provider
          uri: lb://cloud-svc-provider
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
        # Sentinel Route Demo
        - id: httpbin_route
          uri: https://httpbin.org
          predicates:
            - Path=/httpbin/**
          filters:
            - RewritePath=/httpbin/(?<segment>.*), /$\{segment}