FROM openjdk:8u275
MAINTAINER XingYu.lu

#创建目录并复制文件
RUN mkdir -p /opt/grpc-client && mkdir -p /opt/grpc-client/logs && echo "Asia/Shanghai">/etc/timezone

COPY ./grpc-client/target/wave-flux-grpc-client.jar /opt/grpc-client/wave-flux-grpc-client.jar

EXPOSE 8081
EXPOSE 9090

WORKDIR /opt/grpc-client

ENTRYPOINT java -jar /opt/grpc-client/wave-flux-grpc-client.jar --spring.profiles.active=prod