FROM openjdk:8u275
MAINTAINER XingYu.lu

#创建目录并复制文件
RUN mkdir -p /opt/grpc-server && mkdir -p /opt/grpc-server/logs && echo "Asia/Shanghai">/etc/timezone

COPY ./grpc-server/target/wave-flux-grpc-server.jar /opt/grpc-server/wave-flux-grpc-server.jar

EXPOSE 8080
EXPOSE 50101

WORKDIR /opt/grpc-server

ENTRYPOINT java -jar /opt/grpc-server/wave-flux-grpc-server.jar --spring.profiles.active=prod