server:
  port: 18008

management:
  endpoints:
    web:
      exposure:
        include: health,info
spring:
  #  profiles:
  #    active: @env@
  application:
    name: cloud-svc-consumer
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: aa23932f-daff-4188-994f-ceff3f8d9749
        group: local
      config:
        namespace: aa23932f-daff-4188-994f-ceff3f8d9749
        group: local
        name: spring-datatsource
        file-extension: yaml
        refresh-enabled: true
        # 启用远程同步配置
        enable-remote-sync-config: true
  config:
    #  Nacos 在 Cloud 中 dataId 的完整格式：${prefix}-${spring.profiles.active}.${file-extension}
    #  prefix 默认为 spring.application.name 的值
    import:
      - nacos:${spring.application.name}-${spring.cloud.nacos.config.name}.${spring.cloud.nacos.config.file-extension}
logging:
  level:
    com.baomidou: debug
    com.alibaba.cloud.nacos.configdata: info
feign:
  sentinel:
    enabled: true